### ISSUE TITLE
Enhancements to work with lists/leaf-lists in RESTCONF

### ISSUE THREAD

**Issue by wisotzky** [netconf-wg/restconf-next#1]
RESTCONF GET operations do not provide control about the amount of data being returned. While max-depth can be used to limit the number of hierarchy levels, it does not help if a table contains 100.000's of entries. The way RESTCONF works today - you can request either the entire table (all entries or nothing).

To following functionality is requested:
- Option to limit the number of entries returned when reading a list [P0]
- Method to check, if a list/container contains explicitly configured data without the need to read the (entire) list/container [P0]
- Method to get the number of list entries, without the need to reed the entire list [P1]
- Method to get timestamp, when the list of updated the last time [P1]
- Method to retrive a table in chunks aka paging [P1]

Same functionality has been requested for NETCONF. So feature should be aligned between both protocol stack.

**Comment by sunseawq** [comment]
I think the title should be changed into "Enhacement to work with litsts/leaf lists in RESTCONF".

**Comment by avtobiff** [comment]
This can be closed since this work is ongoing in the internet drafts about transaction-id [0]
and list-pagination for yang-driven protocols [1,2]

[0] https://datatracker.ietf.org/doc/draft-ietf-netconf-transaction-id/
[1] https://datatracker.ietf.org/doc/draft-ietf-netconf-list-pagination/
[2] https://datatracker.ietf.org/doc/draft-ietf-netconf-list-pagination-rc/
